export const HANDLE_LOGIN = "HANDLE_LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";

export const SAVE_ACCOUNT_DETAILS_SUCCESS = "SAVE_ACCOUNT_DETAILS_SUCCESS";

export const SAVE_LENDER_DETAILS = "SAVE_LENDER_DETAILS";
export const SAVE_BENEFICIARY_DETAILS = "SAVE_BENEFICIARY_DETAILS";
export const HANDLE_BENEFICIARIES_PERCENTAGE = "HANDLE_BENEFICIARIES_PERCENTAGE";

export const ENABLE_NEXT_BTN = "ENABLE_NEXT_BTN";
export const ENABLE_ADD_BTN = "ENABLE_ADD_BTN";

export const INITIATE_SAVE_LENDER_PROFILE_DETAILS = "INITIATE_SAVE_LENDER_PROFILE_DETAILS";
export const SAVE_LENDER_PROFILE_DETAILS_FAILED = "SAVE_LENDER_PROFILE_DETAILS_FAILED";
export const SAVE_LENDER_PROFILE_DETAILS_SUCCESS = "SAVE_LENDER_PROFILE_DETAILS_SUCCESS";

export const UPDATE_LENDER_PROFILE_DETAILS = "UPDATE_LENDER_PROFILE_DETAILS";
export const UPDATE_LENDER_PROFILE_DETAILS_SUCCESS = "UPDATE_LENDER_PROFILE_DETAILS_SUCCESS";
export const UPDATE_LENDER_PROFILE_DETAILS_FAILED = "UPDATE_LENDER_PROFILE_DETAILS_FAILED";

export const INIT_GET_LENDER_PROFILE_DETAILS = "INIT_GET_LENDER_PROFILE_DETAILS";
export const GET_LENDER_PROFILE_DETAILS_SUCCESS = "GET_LENDER_PROFILE_DETAILS_SUCCESS";
export const GET_LENDER_PROFILE_DETAILS_FAILED = "GET_LENDER_PROFILE_DETAILS_FAILED";